name: ABC Daily Schedule

on:
  workflow_dispatch:
  schedule:
    # 每天北京时间 10:00（UTC 2:00）
    - cron: '0 2 * * *'

jobs:
  run-docker:
    runs-on: ubuntu-latest
    env:
      default_vender: ${{ vars.default_vender }}
      YOUTUBE_LINK: "https://www.youtube.com/playlist?list=PLQOa26lW-uI_V2Ux6Iwcr0me-RjB8gZaF"
      episode_number: ${{ vars.episode_number }}
    steps:
      - name: Login to Tencent Cloud Container Registry
        run: |
          set +e
          count=0
          while true; do
            docker login ccr.ccs.tencentyun.com -u ${{ secrets.TENCENT_CLOUD_USERNAME }} -p ${{ secrets.TENCENT_CLOUD_PASSWORD }}
            docker pull ccr.ccs.tencentyun.com/runtimeerr/aigc:youtube-video-maker
            if [ $? -eq 0 ]; then
              break
            fi
            count=$((count+1))
            if [ $count -gt 5 ]; then
              echo "Failed to login to Tencent Cloud Container Registry after 5 attempts"
              exit 1
            fi
            sleep 10
          done
      
      - name: Run Docker container
        run: |
          lscpu
          lsmem
          export default_vender=siliconflow
          export publish_title_prefix="【ABC News】`date '+%Y.%m.%d'`-"
          docker run -e default_vender=$default_vender -e YOUTUBE_LINK="$YOUTUBE_LINK" -e episode_number=$episode_number -e publish_title_prefix="$publish_title_prefix" ccr.ccs.tencentyun.com/runtimeerr/aigc:youtube-video-maker 