name: CNN Daily Schedule

on:
  workflow_dispatch:
  schedule:
    # 每天北京时间 15:00（UTC 7:00）
    - cron: '0 7 * * *'

jobs:
  run-docker:
    runs-on: ubuntu-latest
    env:
      default_vender: ${{ vars.default_vender }}
      YOUTUBE_LINK: "https://www.youtube.com/playlist?list=PL6XRrncXkMaWWFyjMtzWWSeOocFr-N_3s"
      episode_number: ${{ vars.episode_number }}
    steps:
      - name: Login to Tencent Cloud Container Registry
        run: |
          set +e
          count=0
          while true; do
            docker login ccr.ccs.tencentyun.com -u ${{ secrets.TENCENT_CLOUD_USERNAME }} -p ${{ secrets.TENCENT_CLOUD_PASSWORD }}
            docker pull ccr.ccs.tencentyun.com/runtimeerr/aigc:youtube-video-maker
            if [ $? -eq 0 ]; then
              break
            fi
            count=$((count+1))
            if [ $count -gt 5 ]; then
              echo "Failed to login to Tencent Cloud Container Registry after 5 attempts"
              exit 1
            fi
            sleep 10
          done
      
      - name: Run Docker container
        run: |
          export publish_title_prefix="【CNN News】`date '+%Y.%m.%d'`-"
          export use_video_frame_as_cover=1
          export default_vender=aliyun
          docker run -e default_vender=$default_vender -e YOUTUBE_LINK="$YOUTUBE_LINK" -e episode_number=$episode_number -e publish_title_prefix="$publish_title_prefix" -e use_video_frame_as_cover=$use_video_frame_as_cover ccr.ccs.tencentyun.com/runtimeerr/aigc:youtube-video-maker 