name: Manual Trigger
on:
  workflow_dispatch:
    inputs:
      default_vender:
        description: 'Openai供应商 aliyun/glm/siliconflow'
        required: true
        default: 'glm'
      YOUTUBE_LINK:
        description: 'youtube地址'
        required: false
        default: 'https://www.youtube.com/@wsj/videos'
      episode_number:
        description: '集数'
        required: true
        default: 1

jobs:
  run-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Tencent Cloud Container Registry
        run: |
          docker login ccr.ccs.tencentyun.com -u ${{ secrets.TENCENT_CLOUD_USERNAME }} -p ${{ secrets.TENCENT_CLOUD_PASSWORD }}
      
      - name: Run Video Cut
        run: |
          lscpu
          lsmem
          echo "openai供应商: ${{ github.event.inputs.default_vender }}"
          echo "youtube地址: ${{ github.event.inputs.YOUTUBE_LINK }}"
          echo "episode_number: ${{ github.event.inputs.episode_number }}"
          export default_vender=${{ github.event.inputs.default_vender }}
          export YOUTUBE_LINK="${{ github.event.inputs.YOUTUBE_LINK }}"
          export episode_number=${{ github.event.inputs.episode_number }}

          docker run -e default_vender=$default_vender -e YOUTUBE_LINK="$YOUTUBE_LINK" -e episode_number=$episode_number ccr.ccs.tencentyun.com/runtimeerr/aigc:youtube-video-maker 