name: Fox News Daily Schedule

on:
  workflow_dispatch:
  schedule:
    # 每天北京时间 13:00（UTC 5:00）
    - cron: '0 5 * * *'

jobs:
  run-docker:
    runs-on: ubuntu-latest
    env:
      YOUTUBE_LINK: ${{ vars.YOUTUBE_LINK }}
      episode_number: ${{ vars.episode_number }}
    steps:
      - name: Login to Tencent Cloud Container Registry
        run: |
          set +e
          count=0
          while true; do
            docker login ccr.ccs.tencentyun.com -u ${{ secrets.TENCENT_CLOUD_USERNAME }} -p ${{ secrets.TENCENT_CLOUD_PASSWORD }}
            docker pull ccr.ccs.tencentyun.com/runtimeerr/aigc:youtube-video-maker
            if [ $? -eq 0 ]; then
              break
            fi
            count=$((count+1))
            if [ $count -gt 5 ]; then
              echo "Failed to login to Tencent Cloud Container Registry after 5 attempts"
              exit 1
            fi
            sleep 10
          done
      
      - name: Run Docker container
        run: |
          lsmem
          lscpu
          export YOUTUBE_LINK="https://www.youtube.com/playlist?list=PLlTLHnxSVuIz6_eSi1Tvt3C4eXEg5MHV3"  
          export publish_title_prefix="【Fox News】`date '+%Y.%m.%d'`-"
          docker run -e YOUTUBE_LINK="$YOUTUBE_LINK" -e episode_number=1 -e publish_title_prefix="$publish_title_prefix" ccr.ccs.tencentyun.com/runtimeerr/aigc:youtube-video-maker 